[[cells]]
name = "freight"
enable_type_id = true
location = { file = "build/release/freight" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x7992ab48ed6cea6a3455e7e8717da2c096284710"
hash_type = "type"

